In [1]:
import pandas as pd
data = pd.read_csv("bivi_watsons_sellout_2122.csv")
maping = pd.read_csv("Product_Mapping.csv")

maping =maping.drop(['PLU','Barcode'],axis = 1)
header = ['default_code','product_name']
maping.columns = header

In [2]:
maping

     default_code                                       product_name
0            1486          Wardah Nutri Shine Shampoo 170 ml (Pc(s))
1            4576   Wardah Hairfall Treatment Shampoo 170 ml (Pc(s))
2            1488          Wardah Daily Fresh Shampoo 170 ml (Pc(s))
3            1485        Wardah Anti Dandruff Shampoo 170 ml (Pc(s))
4            1884  Wardah Scentsation Purity Eau De Toilette 35 m...
..            ...                                                ...
219          4544            Kahf True Brotherhood Essential Package
220          4551             Kahf Skin Protection Essential Package
221          3112              Wardah Bundling White Secret - Watson
222          3748  LABORE Sensitive Skin Care GentleBiome Mild Cl...
223          3893  Kahf Triple Action Oil and Comedo Defense Face...

[224 rows x 2 columns]

In [3]:
temp = pd.merge(data,maping,on='product_name')

In [4]:
temp

,day,month,year,partner_ref,partner_name,product_name,daily_sales_qty,default_code
0,1,1,2022,118191-002,WATSONS BUAH BATU,Wardah Acnederm Night Treatment Moisturizer 40...,1,1578
1,1,1,2022,118191-043,WATSONS MALL ARTHA GADING (MAG),Wardah Acnederm Night Treatment Moisturizer 40...,3,1578
2,1,1,2022,118191-051,WATSONS MALL MARGO CITY (MMC),Wardah Acnederm Night Treatment Moisturizer 40...,1,1578
3,1,1,2022,118191-071,WATSONS SOLO PARAGON LIFESTYLE MALL (SPL),Wardah Acnederm Night Treatment Moisturizer 40...,1,1578
4,1,1,2022,118191-136,WATSONS LIPPO CIKARANG,Wardah Acnederm Night Treatment Moisturizer 40...,2,1578
...,...,...,...,...,...,...,...,...
192205,30,6,2022,118191-108,WATSONS RAMAYANA SAMARINDA,Kahf Triple Action Oil and Comedo Defense Face...,1,3893
192206,30,6,2022,118191-121,WATSONS SUNTER MALL,Kahf Triple Action Oil and Comedo Defense Face...,1,3893
192207,30,6,2022,118191-155,WATSONS THE PARK SAWANGAN DEPOK,Kahf Triple Action Oil and Comedo Defense Face...,1,3893
192208,12,6,2021,118191-038,WATSONS LOTTE MART BINTARO,Wardah Nature Daily Aloe Hydramild Hand Wash 2...,10,2519
192209,13,6,2021,138701-023,WATSONS LOKASARI SQUARE (LSS),Wardah Nature Daily Aloe Hydramild Hand Wash 2...,2,2519

In [5]:
data[data.

SyntaxError: unexpected EOF while parsing (3673573493.py, line 1)

In [ ]:
maping[maping.default_code ==3775]

In [ ]:
data[data.product_name =="MAKE OVER Powerstay Demi-Matte Cover Cushion C31 Pink Beige 15 g"]

In [ ]:
maping[maping.default_code ==90]

In [8]:
data.partner_name.value_counts()

WATSONS PONDOK INDAH MALL (PIM)           32148
WATSONS MALL KOTA KASABLANKA (MKK)        31244
WATSONS BOTANI SQUARE (BTS)               22321
WATSONS MALL PANAKKUKANG                  17675
WATSONS BOGOR TRADE MALL (BTM)            17363
                                          ...
WATSONS DISCOVERY MALL BALI                 273
WATSONS VETERAN BINTARO STREET              236
WATSONS CITY PLAZA KLENDER                  222
WATSONS SAPPHIRE BEKASI STREET - PUTUS      164
WATSONS KIARA CONDONG                       135
Name: partner_name, Length: 179, dtype: int64

In [9]:
data.product_name.value_counts()

Wardah EyeXpert Optimum Hi-Black Liner 1 gr (Pc(s))                  15106
Emina Sun Battle SPF 30 PA+++ 60 ml                                  13715
Emina Glossy Stain 01 Autumn Bell 3 g                                13521
Wardah UV Shield Essential Sunscreen Gel SPF 30 (New Blister)        10179
Wardah EyeXpert The Volume Expert Mascara 7 gr (Pc(s))               10150
                                                                     ...
Emina Eye Do! Pencil Eye Liner Gold 1 gr (Pc(s))                         1
MAKE OVER Sparkling Powder Gold 2 g (Pc(S))                              1
Refill Perfect Cov. TWC 02 Coral, 14 gr                                  1
Wardah Crystal Skin Package                                              1
MAKE OVER Tities Sapoetra Intense Matte Lip Cream Buttercup 6.5 g        1
Name: product_name, Length: 1711, dtype: int64

In [10]:
data

,day,month,year,partner_ref,partner_name,product_name,daily_sales_qty
0,1,1,2022,118191-002,WATSONS BUAH BATU,Wardah Acnederm Night Treatment Moisturizer 40...,1
1,1,1,2022,118191-004,WATSONS FESTIVAL CITYLINK,Wardah C-Defense Energizing Creamy Wash 60 ml ...,1
2,1,1,2022,118191-004,WATSONS FESTIVAL CITYLINK,Wardah Everyday BB Cream Natural 15 ml (Pc(s)),1
3,1,1,2022,118191-004,WATSONS FESTIVAL CITYLINK,Wardah Everyday Fruity Sheer Lip Balm Grape 4 g,1
4,1,1,2022,118191-004,WATSONS FESTIVAL CITYLINK,Wardah Everyday Fruity Sheer Lip Balm Strawber...,1
...,...,...,...,...,...,...,...
1135485,31,12,2021,138701-203,WATSONS TEBET STREET,Wardah Lightening Matte Powder 01 Light Beige ...,1
1135486,31,12,2021,138701-203,WATSONS TEBET STREET,Wardah Lightening Matte Powder 02 Beige 20 g,1
1135487,31,12,2021,138701-203,WATSONS TEBET STREET,Wardah Lipstick Longlasting 02 Pink Sorbet 2.3...,1
1135488,31,12,2021,138701-203,WATSONS TEBET STREET,Wardah Olive Oil For Massage 150 ml,1
1135489,31,12,2021,138701-203,WATSONS TEBET STREET,Wardah Roll On For Her 60 ml,1

In [11]:
data[data.daily_sales_qty <= 0]

Empty DataFrame
Columns: [day, month, year, partner_ref, partner_name, product_name, daily_sales_qty]
Index: []

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1135490 entries, 0 to 1135489
Data columns (total 7 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   day              1135490 non-null  int64
 1   month            1135490 non-null  int64
 2   year             1135490 non-null  int64
 3   partner_ref      1135490 non-null  object
 4   partner_name     1135490 non-null  object
 5   product_name     1132916 non-null  object
 6   daily_sales_qty  1135490 non-null  int64
dtypes: int64(4), object(3)
memory usage: 60.6+ MB

In [17]:
data.partner_name.nunique()

179

In [13]:
data[data.product_name.isna() ==True]

,day,month,year,partner_ref,partner_name,product_name,daily_sales_qty
9,1,1,2022,118191-004,WATSONS FESTIVAL CITYLINK,NaN,1
33,1,1,2022,118191-005,WATSONS JATINANGOR TOWN SQUARE (JATOS),NaN,1
62,1,1,2022,118191-014,WATSONS RAMAYANA KARAWANG,NaN,1
271,1,1,2022,118191-037,WATSONS LOKASARI SQUARE (LSS),NaN,2
278,1,1,2022,118191-039,WATSONS LOTTE MART FATMAWATI,NaN,1
...,...,...,...,...,...,...,...
1135190,31,12,2021,138701-141,WATSONS MAJALAYA BANDUNG,NaN,1
1135247,31,12,2021,138701-150,WATSONS GALAXY MALL 2 SURABAYA,NaN,1
1135277,31,12,2021,138701-151,WATSONS GANDARIA CITY,NaN,1
1135319,31,12,2021,138701-153,WATSONS PURI INDAH MALL,NaN,1
1135354,31,12,2021,138701-159,WATSONS METROPOLITAN MALL BEKASI,NaN,1